name: hrk_test_batteries
version: 0.1.0-pre.1

description: >-
  A library to accumulate required dart test helper and utility codes
repository: https://github.com/hrishikesh-kadam/hrk_test_batteries.dart
topics:
  - batteries
  - dart-batteries
  - dart-test-batteries

environment:
  sdk: ^3.0.0

dependencies:
  test: ^1.24.4
  checks: '>=0.3.0 <1.0.0'

dev_dependencies:
  hrk_analysis: ^1.0.0
